


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;ET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Time Recurrence Unit" AS ENUM (
    'Daily',
    'Weekly',
    'Monthly',
    'Yearly'
);


ALTER TYPE "public"."Time Recurrence Unit" OWNER TO "postgres";


COMMENT ON TYPE "public"."Time Recurrence Unit" IS 'Units of time that something may recur in.';



CREATE OR REPLACE FUNCTION "public"."get_simulators_with_images"() RETURNS SETOF "jsonb"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $$
select jsonb_agg(
  jsonb_build_object(
    'sim', s,
    'images', (
      select jsonb_agg(
        jsonb_build_object(
          'url', concat('https://bvxxbkafrjoboauypopg.supabase.co/storage/v1/object/public/', o.bucket_id, '/', o.name),
          'alt', i.alt
        )
      )
      from simulator_images i
      left join storage.objects o on i.image_id = o.id
      where i.simulator_id = s.id
      order by MIN(i.display_order)
    )
  )
)
from simulators s;
$$;


ALTER FUNCTION "public"."get_simulators_with_images"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."calendar_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "tags" "text"[] DEFAULT '{}'::"text"[] NOT NULL
);


ALTER TABLE "public"."calendar_events" OWNER TO "postgres";


ALTER TABLE "public"."calendar_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."calendar_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."recurring_calendar_events" (
    "id" bigint NOT NULL,
    "frequency" "public"."Time Recurrence Unit" NOT NULL
);


ALTER TABLE "public"."recurring_calendar_events" OWNER TO "postgres";


ALTER TABLE "public"."recurring_calendar_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."recurring_calendar_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."simulator_images" (
    "image_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "alt" "text" DEFAULT ''::"text" NOT NULL,
    "simulator_id" "text" NOT NULL,
    "display_order" smallint DEFAULT '0'::smallint NOT NULL
);


ALTER TABLE "public"."simulator_images" OWNER TO "postgres";


COMMENT ON TABLE "public"."simulator_images" IS 'Mapping images to simulators';



COMMENT ON COLUMN "public"."simulator_images"."display_order" IS 'Lower values are ordered first.';



CREATE TABLE IF NOT EXISTS "public"."simulators" (
    "id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "active" boolean DEFAULT false NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "price" real NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "accessibility_details" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."simulators" OWNER TO "postgres";


COMMENT ON TABLE "public"."simulators" IS 'Core information on the simulators currently available to book.';



ALTER TABLE ONLY "public"."calendar_events"
    ADD CONSTRAINT "calendar_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recurring_calendar_events"
    ADD CONSTRAINT "recurring_calendar_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."simulator_images"
    ADD CONSTRAINT "simulator_images_pkey" PRIMARY KEY ("image_id", "simulator_id");



ALTER TABLE ONLY "public"."simulators"
    ADD CONSTRAINT "simulators_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."simulator_images"
    ADD CONSTRAINT "images_id_fkey" FOREIGN KEY ("image_id") REFERENCES "storage"."objects"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recurring_calendar_events"
    ADD CONSTRAINT "recurring_calendar_events_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."calendar_events"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."simulator_images"
    ADD CONSTRAINT "simulator_images_simulator_id_fkey" FOREIGN KEY ("simulator_id") REFERENCES "public"."simulators"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."simulator_images" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."simulators" FOR SELECT USING (true);



ALTER TABLE "public"."calendar_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recurring_calendar_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."simulator_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."simulators" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."get_simulators_with_images"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_simulators_with_images"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_simulators_with_images"() TO "service_role";



GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."calendar_events" TO "anon";
GRANT ALL ON TABLE "public"."calendar_events" TO "authenticated";
GRANT ALL ON TABLE "public"."calendar_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."calendar_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."calendar_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."calendar_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."recurring_calendar_events" TO "anon";
GRANT ALL ON TABLE "public"."recurring_calendar_events" TO "authenticated";
GRANT ALL ON TABLE "public"."recurring_calendar_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."recurring_calendar_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."recurring_calendar_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."recurring_calendar_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."simulator_images" TO "anon";
GRANT ALL ON TABLE "public"."simulator_images" TO "authenticated";
GRANT ALL ON TABLE "public"."simulator_images" TO "service_role";



GRANT ALL ON TABLE "public"."simulators" TO "anon";
GRANT ALL ON TABLE "public"."simulators" TO "authenticated";
GRANT ALL ON TABLE "public"."simulators" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































drop extension if exists "pg_net";

alter table "public"."recurring_calendar_events" drop constraint "recurring_calendar_events_id_fkey";

alter table "public"."simulator_images" drop constraint "simulator_images_simulator_id_fkey";

alter table "public"."recurring_calendar_events" alter column "frequency" set data type public."Time Recurrence Unit" using "frequency"::text::public."Time Recurrence Unit";

alter table "public"."recurring_calendar_events" add constraint "recurring_calendar_events_id_fkey" FOREIGN KEY (id) REFERENCES public.calendar_events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recurring_calendar_events" validate constraint "recurring_calendar_events_id_fkey";

alter table "public"."simulator_images" add constraint "simulator_images_simulator_id_fkey" FOREIGN KEY (simulator_id) REFERENCES public.simulators(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."simulator_images" validate constraint "simulator_images_simulator_id_fkey";


